// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIvSOPVkn-2SRtv0K6ujbShd4JQTubiY',
    appId: '1:41462146256:web:238c12ac07bdbda57cead5',
    messagingSenderId: '41462146256',
    projectId: 'pethotelappfirebase',
    authDomain: 'pethotelappfirebase.firebaseapp.com',
    databaseURL: 'https://pethotelappfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'pethotelappfirebase.appspot.com',
    measurementId: 'G-2QMYHR2CZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJDdofFKEXXqj7HyAqIIjTbue10DObjk',
    appId: '1:41462146256:android:f9586b01c6b55bce7cead5',
    messagingSenderId: '41462146256',
    projectId: 'pethotelappfirebase',
    databaseURL: 'https://pethotelappfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'pethotelappfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGp5Z4vd54j4PV8kdbZYesr7KgXFXT04',
    appId: '1:41462146256:ios:7b194e2d6ddd17f37cead5',
    messagingSenderId: '41462146256',
    projectId: 'pethotelappfirebase',
    databaseURL: 'https://pethotelappfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'pethotelappfirebase.appspot.com',
    iosClientId: '41462146256-ubd931qp62frhmg6p82qfu272jc6qsl6.apps.googleusercontent.com',
    iosBundleId: 'com.unclecurly320.petserviceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXGp5Z4vd54j4PV8kdbZYesr7KgXFXT04',
    appId: '1:41462146256:ios:5ee13d1f63e774037cead5',
    messagingSenderId: '41462146256',
    projectId: 'pethotelappfirebase',
    databaseURL: 'https://pethotelappfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'pethotelappfirebase.appspot.com',
    iosClientId: '41462146256-vubb5j9mjecv9uakirhrdm5gnm19ftte.apps.googleusercontent.com',
    iosBundleId: 'com.unclecurly320.petserviceapp.RunnerTests',
  );
}
